// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tokomtzixxoeomgetzya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRva29tdHppeHhvZW9tZ2V0enlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTk4NjAsImV4cCI6MjA2MjA5NTg2MH0.ULDswcN1-es1hHtPGZNxDbJiAZhyv4TyCe6ums87nYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);